### ISSUE TITLE
Pointers to where to look for kube-service-bindings integration

### ISSUE THREAD

**Issue by mhdawson** [nodeshift-blog-examples/kube-service-bindings-examples#3]
Either in the initial readme or in the readme for each sub-example we should point people to the file that includes the kube-service-bindings integration.

**Comment by pacostas** [comment]
I'm not sure If I quite follow you on the term integrations. AFAIK on the initial [readme](https://github.com/nodeshift-blog-examples/kube-service-bindings-examples/blob/main/README.md#kube-service-bindings) each bullet from the list points to corresponding example/integration except the kafka examples which has instructions by their own.

**Comment by mhdawson** [comment]
What I meant is the examples have lots of file/code. As a set of examples highlighting kube-service-bindings it would be good in the README to point people directly to the file that contains the use of kube-service-bindings so that they can easily find that.

**Comment by pacostas** [comment]
https://github.com/nodeshift-blog-examples/kube-service-bindings-examples/pull/10

**Comment by mhdawson** [comment]
@pacostas thanks for the PR, landed, closing this issue.
