### ISSUE TITLE
General explanation of the app

### ISSUE THREAD

**Issue by mhdawson** [nodeshift-blog-examples/kube-service-bindings-examples#4]
I would be good to have somewhere a basic intro overview of the sample app used by most of the examples.  Explaining that most f the code is the same and then letting people know what is specific/where to find the client specific code in each case.

**Comment by pacostas** [comment]
Sure, I can create a section on the main readme file called Node.js App Architecture and pointing there from each sub-example. The only difference per app is the lib/db/index.js and lib/queries/fruits.js files. Mongodb and mongoose are not 100% aligned but a small refactor will do the trick :) . About the rhea and kafka examples I dont think I can do something about them right now for having a similar architecture.

**Comment by mhdawson** [comment]
> About the rhea and kafka examples I dont think I can do something about them right now for having a similar architecture. 

understood

>  Sure, I can create a section on the main readme file called Node.js App Architecture and pointing there from each sub-example. The only difference per app is the lib/db/index.js and lib/queries/fruits.js files. Mongodb and mongoose are not 100% aligned but a small refactor will do the trick :)

Sounds good

**Comment by pacostas** [comment]
https://github.com/nodeshift-blog-examples/kube-service-bindings-examples/pull/9

**Comment by mhdawson** [comment]
Thanks for the PR, landed, closing this issue.
