### ISSUE TITLE
Code for example is missing for rhea example

### ISSUE THREAD

**Issue by mhdawson** [nodeshift-blog-examples/kube-service-bindings-examples#5]
It looks like the code for the rhea example was missing from the main PR.

**Comment by pacostas** [comment]
Correct. The example is this one https://github.com/nodeshift-starters/nodejs-messaging-work-queue. Question is should I point them to this repo or copy this repo under kube-service-bindgins-examples?

**Comment by mhdawson** [comment]
@pacostas pointing to the repo is my preference to avoid duplciation, we just need to make it obvious how/where you get the code from.

**Comment by pacostas** [comment]
https://github.com/nodeshift-blog-examples/kube-service-bindings-examples/pull/8

**Comment by mhdawson** [comment]
@pacostas thanks, looks good.
